services:
  fika-bot:
    build: .
    env_file: .env
    restart: unless-stopped
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python -u main.py
    volumes:
      - .:/app
    working_dir: /app
    depends_on: []
